# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XckgS345TOu8I9LpOd47ksOaj0k9TJRe
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from sklearn import linear_model
import pickle

# %matplotlib inline

df = pd.read_csv('canada_per_capita_income.csv')
df


from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('per_capita_income',axis=1),df.per_capita_income,test_size=(9/46))

len_reg = linear_model.LinearRegression()
model = len_reg.fit(x_train,y_train)

len_reg.predict(x_test)

len_reg.score(x_test,y_test)

pickle.dump(len_reg, open('model.pkl','wb'))

print(len_reg.predict([[2020]]))